#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include "reflect/registry.hpp"


REFLECT_REGISTER_RTTI_TYPE_MANUAL(int8_t);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(int16_t);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(int32_t);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(int64_t);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(uint8_t);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(uint16_t);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(uint32_t);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(uint64_t);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(float);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(double);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(char);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(std::string);
REFLECT_REGISTER_RTTI_TYPE_MANUAL(std::vector<std::string>);
